version: "3.3"

volumes:
  db-socket:
  db-data:
  app-images:

services:
  app:
    build: php
    working_dir: /app
    command: sudo -u http -- /usr/bin/php -S 0.0.0.0:${PORT:-8081} -t /app
    ports:
      - "${PORT:-8081}:${PORT:-8081}"
    volumes:
      - ../:/app:ro
      - db-socket:/run/mysqld
      - app-images:/app/images
    tmpfs:
      - /app/cache
    depends_on:
      - db

  db:
    build: mariadb
    command: mysqld
    user: mysql
    network_mode: none
    volumes:
      - db-data:/var/lib/mysql
      - db-socket:/run/mysqld
